fix: use macos-13 for runners
macos-15 uses too new a version of python which lacks support for `pipes`, which is used by our old foreign_cc version.

```
rules_foreign_cc: Printing build logs:
  /bin/bash -c bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-1710242dce5b/bin/external/rules_foreign_cc/toolchains/ninja_tool_foreign_cc/wrapper_build_script.sh)
_____ BEGIN BUILD LOGS _____
+ ./configure.py --bootstrap
Traceback (most recent call last):

  File "/private/var/tmp/_bazel_runner/f7b5b126cb65bf12475e292acf07553d/sandbox/darwin-sandbox/120/execroot/proxy_wasm_cpp_host/bazel-out/darwin_arm64-opt-exec-2B5CBBC6-ST-1710242dce5b/bin/external/rules_foreign_cc/toolchains/ninja.build_tmpdir/./configure.py", line 26, in <module>
    import pipes
ModuleNotFoundError: No module named 'pipes'
```

Signed-off-by: Matt Leon <mattleon@google.com>