fix: First attempt at cargo-raze -> crate_universe
Had to update platforms for crate_universe compatibility.
Had to update Abseil due to local build issues.

Wasmsign is not quite working yet (wasmtime not tried yet):
```
$ bazelisk test --verbose_failures --test_output=errors --define engine=null --config=clang -- //test/...
...
ERROR: /usr/local/google/home/mstevenson/git/proxy-wasm-cpp-host/test/test_data/BUILD:22:17: in (an implicit dependency) attribute of wasm_rust_binary_rule rule //test/test_data:abi_export.wasm: @crates_vendor__wasmsign-0.1.2//:wasmsign does not refer to a valid executable target. Since this rule was created by the macro 'wasm_rust_binary', the error might have been caused by the macro implementation
ERROR: /usr/local/google/home/mstevenson/git/proxy-wasm-cpp-host/test/test_data/BUILD:22:17: Analysis of target '//test/test_data:abi_export.wasm' failed
```

Signed-off-by: Martijn Stevenson <mstevenson@google.com>