add missing <string> include
This appears to be tripping up Windows builds:

```
ERROR: D:/a/proxy-wasm-cpp-host/proxy-wasm-cpp-host/BUILD:64:11: Compiling src/signature_util.cc failed: (Exit 2): cl.exe failed: error executing command (from target //:base_lib)
C:\users\runneradmin\_bazel_runneradmin\dwxiuyix\execroot\proxy_wasm_cpp_host\include/proxy-wasm/signature_util.h(30): error C2039: 'string': is not a member of 'std'
  cd /d C:/users/runneradmin/_bazel_runneradmin/dwxiuyix/execroot/proxy_wasm_cpp_host
```

Signed-off-by: Michael Warres <mpw@google.com>