fix a few missing includes and ::proxy_wasm namespace pollution with std {} (#365)
* include: add missing dependencies

Signed-off-by: Ivan Prisyazhnyy <john.koepi@gmail.com>

* fix: proxy_wasm namespace polution with std defs

fixes:

    In file included from external/proxy_wasm_cpp_host/src/null/null.cc:17:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/null_vm.h:22:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/null_vm_plugin.h:18:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/wasm_vm.h:26:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/word.h:22:
    external/proxy_wasm_cpp_sdk/proxy_wasm_common.h:59:8: error: no type named 'string' in namespace 'proxy_wasm::std'; did you mean '::std::string'?
    inline std::string toString(WasmResult r) {
           ^~~~~~~~~~~
           ::std::string

The headers from https://github.com/proxy-wasm/proxy-wasm-cpp-sdk
include C++ headers that pollute the current namespace with a partial
definition of std{} namespace that then interferes with the names
resolution inside of proxy_wasm as well as duplicates ::std defs.

Signed-off-by: Ivan Prisyazhnyy <john.koepi@gmail.com>

* include: add missing includes to pairs_util and the test

Signed-off-by: Ivan Prisyazhnyy <john.koepi@gmail.com>

* sdk.h/change: drop one redundant namespace hierarchy level

to have

    +using WasmResult = internal::WasmResult;

instead of

    -using WasmResult = internal::proxy_wasm::WasmResult;

the patchset fixes:

    In file included from external/proxy_wasm_cpp_host/src/null/null.cc:17:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/null_vm.h:22:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/null_vm_plugin.h:18:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/wasm_vm.h:26:
    In file included from external/proxy_wasm_cpp_host/include/proxy-wasm/word.h:22:
    external/proxy_wasm_cpp_sdk/proxy_wasm_common.h:59:8: error: no type named 'string' in namespace 'proxy_wasm::std'; did you mean '::std::string'?
    inline std::string toString(WasmResult r) {
           ^~~~~~~~~~~
           ::std::string

The headers from https://github.com/proxy-wasm/proxy-wasm-cpp-sdk
include C++ headers that pollute the current namespace with a partial
definition of std{} namespace that then interferes with the names
resolution inside of proxy_wasm as well as duplicates ::std defs.

Signed-off-by: Ivan Prisyazhnyy <john.koepi@gmail.com>

---------

Signed-off-by: Ivan Prisyazhnyy <john.koepi@gmail.com>